set_property IOSTANDARD LVCMOS33 [get_ports {clk}]
set_property PACKAGE_PIN H4 [get_ports {clk}]

set_property IOSTANDARD LVCMOS33 [get_ports {ui_in[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ui_in[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ui_in[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ui_in[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ui_in[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ui_in[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ui_in[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ui_in[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rst_n}]
set_property IOSTANDARD LVCMOS33 [get_ports {ena}]

set_property PACKAGE_PIN F19 [get_ports {ui_in[0]}]
set_property PACKAGE_PIN E19 [get_ports {ui_in[1]}]
set_property PACKAGE_PIN D20 [get_ports {ui_in[2]}]
set_property PACKAGE_PIN C22 [get_ports {ui_in[3]}]
set_property PACKAGE_PIN F18 [get_ports {ui_in[4]}]
set_property PACKAGE_PIN C18 [get_ports {ui_in[5]}]
set_property PACKAGE_PIN D17 [get_ports {ui_in[6]}]
set_property PACKAGE_PIN B20 [get_ports {ui_in[7]}]
set_property PACKAGE_PIN P20 [get_ports {rst_n}]
set_property PACKAGE_PIN P19 [get_ports {ena}]

set_property IOSTANDARD LVCMOS33 [get_ports {uo_out[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {uo_out[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {uo_out[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {uo_out[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {uo_out[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {uo_out[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {uo_out[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {uo_out[0]}]

set_property PACKAGE_PIN B17 [get_ports {uo_out[0]}]
set_property PACKAGE_PIN A18 [get_ports {uo_out[1]}]
set_property PACKAGE_PIN L14 [get_ports {uo_out[2]}]
set_property PACKAGE_PIN L15 [get_ports {uo_out[3]}]
set_property PACKAGE_PIN L16 [get_ports {uo_out[4]}]
set_property PACKAGE_PIN K16 [get_ports {uo_out[5]}]
set_property PACKAGE_PIN M15 [get_ports {uo_out[6]}]
set_property PACKAGE_PIN M16 [get_ports {uo_out[7]}]


